import { EPISODE_COLLECTION_STATUS } from "@/shared/lib/status-constants";

export const episodeStatusOptions = [
  EPISODE_COLLECTION_STATUS.READY,
  EPISODE_COLLECTION_STATUS.RECORDING,
  EPISODE_COLLECTION_STATUS.CANCEL,
  EPISODE_COLLECTION_STATUS.COMPLETED,
];
